### PR TITLE
Fix login error messages

### LINKED ISSUE #270: Invalid password error messages
I think the server should return a standard message regardless of which "step" has failed within the Authentication process. The reasoning is we don't want to give any extra information to potential hackers. Giving back:
1. "invalid password" 
2. "password" length must be at least 5 characters long
3. Account does not exist.

All give potential information that can narrow down their attack.

My suggestion is HBP returns a simple:
"Invalid username or password".

### PR DESCRIPTION
**Pull request by komninoschat**
Resolves #270.

### CODE REVIEW

File: src/routes/auth/login.ts [hunk 1]
```diff
@@ -74,7 +74,7 @@ async function loginAccount({ body, headers }: Request, res: Response): Promise<
   const account = await selectAccount(body)
 
   if (!account) {
-    return res.boom.badRequest('Account does not exist.')
+    return res.boom.badRequest(typeof password !== 'undefined' ? 'Invalid email or password': 'Invalid email')
```
Comment (elitan) [inline src/routes/auth/login.ts:77]: This is a nice one-liner! 

But could we break it up to increase the code readability + make a comment that we show "Invalid email" for magic link?

**Review by elitan — CHANGES_REQUESTED** [review]

File: src/routes/auth/login.ts (hunk 1 above)
Comment (elitan) [reply src/routes/auth/login.ts:77]: "Good code is code that can be understood by a junior engineer. Great code can be understood by a first year CS freshman. The best code is no code at all."

https://old.reddit.com/r/ExperiencedDevs/comments/nmodyl/drunk_post_things_ive_learned_as_a_sr_engineer/
