### PR TITLE
Fix logout when refresh token is in query and not in cookie

### LINKED ISSUE #355: Logout from nhost-js-sdk throws an error
```
Error: expecting a value for non-nullable variable: refresh_token of type: uuid! in variableValues: {"response":{"errors":[{"extensions":{"path":"$.variableValues","code":"validation-failed"},"message":"expecting a value for non-nullable variable: refresh_token of type: uuid! in variableValues"}],"status":200},"request":{"query":"mutation ($refresh_token: uuid!) {\n  delete_auth_refresh_tokens(where: {refresh_token: {_eq: $refresh_token}}) {\n    affected_rows\n  }\n}\n","variables":{}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/src/index.js:116:35)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'mutation ($refresh_token: uuid!) {\n' +
      '  delete_auth_refresh_tokens(where: {refresh_token: {_eq: $refresh_token}}) {\n' +
      '    affected_rows\n' +
      '  }\n' +
      '}\n',
    variables: { refresh_token: undefined }
  }
}```

### PR DESCRIPTION
**Pull request by SkinyMonkey**
fix #355

### CODE REVIEW

File: src/routes/auth/logout.ts [hunk 1]
```diff
@@ -14,15 +14,19 @@ interface HasuraData {
   auth_refresh_tokens: { account: AccountData }[]
 }
 
-async function logout({ body, cookies, signedCookies }: Request, res: Response): Promise<unknown> {
+async function logout({ body, cookies, signedCookies, query }: Request, res: Response): Promise<unknown> {
```
Comment (hkhamm) [inline src/routes/auth/logout.ts:17]: Doesn't the auth middleware already put the refresh_token, whether it's on the query string or in a cookie, in the request? So, this could be:

```
async function logout({ body, cookies, signedCookies, refresh_token }: RequestExtended
```

Then you don't need to change anything else.

Comment (elitan) [reply src/routes/auth/logout.ts]: Correct
