### PR TITLE
skip empty cursor

### LINKED ISSUE #238: Returns incorrect JWT token
With `JWT_CUSTOM_FIELD=` HBP returns an incorrect JWT Token, including the following custom claim:

```json
'x-hasura-': 'null'
```

### PR DESCRIPTION
**Pull request by elitan**
Fixes #238

### CODE REVIEW

File: src/shared/jwt.ts [hunk 1]
```diff
@@ -89,6 +89,7 @@ export function generatePermissionVariables(
     [`${prefix}default-role`]: role,
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
     ...JWT_CUSTOM_FIELDS.reduce<{ [key: string]: ClaimValueType }>((aggr: any, cursor) => {
+      if (!cursor) return
```
Comment (plmercereau) [inline src/shared/jwt.ts:92]: Probably change:
```js
if (!cursor) return
```
to:
```js
if (cursor) aggr[`${prefix}${kebabCase(cursor)}`] = ...
return aggr
```
